---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-redis
  namespace: argocd
  labels:
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.4.2
    helm:
      releaseName: helm-redis
