---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-cert-manager
  namespace: argocd
  labels:
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: helm-cert-manager
      parameters:
        - name: installCRDs
          value: "true"
