---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-vault
  namespace: argocd
  labels:
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    helm:
      releaseName: helm-vault
      parameters:
        - name: ui.enabled
          value: "true"
        - name: ui.serviceType
          value: LoadBalancer
