---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kube-state-metrics
  namespace: argocd
  labels:
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: kube-state-metrics
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.2.7
    helm:
      releaseName: helm-kube-state-metrics
